name: Deploy Email Service with SSR

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'sql/**'
      - 'apps/admin-spa/**'
      - 'apps/client-spa/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'

    # --- Установка зависимостей ---
    - name: Install dependencies
      run: |
        cd apps/admin-spa && npm ci
        cd ../client-spa && npm ci
        npm ci

    # --- Сборка проектов ---
    - name: Build projects
      run: |
        cd apps/admin-spa && npm run build
        cd ../client-spa && npm run build

    # --- Подготовка deployment ---
    - name: Prepare deployment
      run: |
        mkdir -p deployment
        cp -r src sql package*.json ecosystem.config.cjs deployment/
        
        # Для admin-spa (SSR)
        mkdir -p deployment/apps/admin-spa
        cp apps/admin-spa/{server.js,package*.json} deployment/apps/admin-spa/
        cp -r apps/admin-spa/dist deployment/apps/admin-spa/
        
        # Для client-spa (SPA)
        mkdir -p deployment/apps/client-spa
        cp -r apps/client-spa/dist deployment/apps/client-spa/

    # --- Проверка SSH ---
    - name: Validate SSH Key
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        ssh-keygen -lf key.pem
        rm key.pem
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    # --- Деплой на сервер ---
    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.5
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "deployment/*"
        target: "/root/email-service/"
        overwrite: true
        strip_components: 0
        timeout: 5m

    # --- Настройка сервера ---
    - name: Setup server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Установка зависимостей
          cd /root/email-service
          npm ci --production
          
          # Admin SPA (SSR)
          cd apps/admin-spa
          [ -f .env ] && cp .env .env.bak
          npm ci --production
          [ -f .env.bak ] && mv .env.bak .env
          
          # Client SPA
          cd ../client-spa
          [ -f .env ] && cp .env .env.bak
          npm ci --production
          [ -f .env.bak ] && mv .env.bak .env
          
          # Раздача статики
          rm -rf /var/www/email-service/*
          cp -r apps/admin-spa/dist/client/* /var/www/email-service/admin-spa/
          cp -r apps/client-spa/dist/* /var/www/email-service/client-spa/
          
          # Права
          chown -R www-data:www-data /var/www/email-service
          chmod -R 755 /var/www/email-service
          
          # Перезапуск сервисов
          pm2 reload ecosystem.config.cjs
          pm2 save
          systemctl restart nginx
          
          # Сжатие статики
          node src/jobs/compress-static.js 4 --yes