name: Deploy Email Service, Admin SPA and Client SPA

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'sql/**'
      - 'apps/admin-spa/**'
      - 'apps/client-spa/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'npm'

    # --- admin-spa install ---
    - name: Sync admin-spa dependencies
      working-directory: ./apps/admin-spa
      run: |
        rm -rf node_modules package-lock.json
        npm install
        npm install path-to-regexp@6.3.0 --save-exact

    # --- admin-spa build ---
    - name: Build admin-spa
      working-directory: ./apps/admin-spa
      run: npm run build

    # --- client-spa install ---
    - name: Sync client-spa dependencies
      working-directory: ./apps/client-spa
      run: |
        rm -rf node_modules package-lock.json
        npm install

    # --- client-spa build ---
    - name: Build client-spa
      working-directory: ./apps/client-spa
      run: npm run build

    # --- Подготовка deployment для email-service ---
    - name: Prepare email-service deployment
      run: |
        mkdir -p deployment
        cp -r src deployment/
        cp -r sql deployment/
        cp package.json deployment/
        cp package-lock.json deployment/

    # --- Проверка SSH ключа ---
    - name: Validate SSH Key
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        ssh-keygen -lf key.pem
        rm key.pem
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    # --- Деплой email-service ---
    - name: Deploy email-service
      uses: appleboy/scp-action@v0.1.5
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "deployment/*"
        target: "/root/email-service/"
        rm: false
        overwrite: true
        strip_components: 1
        timeout: 2m

    # --- Деплой admin-spa ---
    - name: Deploy admin-spa
      uses: appleboy/scp-action@v0.1.5
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "apps/admin-spa/dist/*,apps/admin-spa/server.js,apps/admin-spa/package.json,apps/admin-spa/package-lock.json"
        target: "/root/email-service/apps/admin-spa/"
        rm: false
        overwrite: true
        strip_components: 2
        timeout: 2m

    # --- Деплой client-spa ---
    - name: Deploy client-spa
      uses: appleboy/scp-action@v0.1.5
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "apps/client-spa/dist/*,apps/client-spa/server.js,apps/client-spa/package.json,apps/client-spa/package-lock.json"
        target: "/root/email-service/apps/client-spa/"
        rm: false
        overwrite: true
        strip_components: 2
        timeout: 2m

    # --- Установка зависимостей и перезапуск сервисов ---
    - name: Install dependencies, copy builds and restart services
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 178.250.247.67
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # email-service
          cd /root/email-service
          rm -rf node_modules
          npm ci --production
          
          # admin-spa
          cd /root/email-service/apps/admin-spa
          [ -f .env ] && cp .env .env.backup
          rm -rf node_modules
          npm ci --production
          [ -f .env.backup ] && mv .env.backup .env
          
          # client-spa
          cd /root/email-service/apps/client-spa
          [ -f .env ] && cp .env .env.backup
          rm -rf node_modules
          npm ci --production
          [ -f .env.backup ] && mv .env.backup .env
          
          # Копируем билды в nginx директории
          rm -rf /var/www/email-service/admin-spa/*
          cp -r /root/email-service/apps/admin-spa/dist/* /var/www/email-service/admin-spa/
          
          rm -rf /var/www/email-service/client-spa/*
          cp -r /root/email-service/apps/client-spa/dist/* /var/www/email-service/client-spa/

          # Сжатие .gz файлов
          node ./src/jobs/compress-static.js /var/www/email-service/admin-spa /var/www/email-service/client-spa
          
          # Перезапуск сервисов
          cd /root/email-service
          pm2 reload ecosystem.config.cjs
          pm2 save